# Practica con libreria numpy

In [6]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

array_1 = np.arange(0, 100, 1)
array_2 = np.linspace(0,10,100)
df_data=pd.DataFrame(columns=["Columna1"],data=array_2)
print(df_data.sample(10))

    Columna1
41  4.141414
20  2.020202
10  1.010101
75  7.575758
9   0.909091
90  9.090909
65  6.565657
89  8.989899
3   0.303030
86  8.686869


In [21]:
df_data["random"] = df_data.loc[:,["Columna1"]]*10
print(df_data.head(5))

   Columna1    random
0   0.00000  0.000000
1   0.10101  1.010101
2   0.20202  2.020202
3   0.30303  3.030303
4   0.40404  4.040404


# Testing con condiciones

In [23]:
x = np.linspace(1, 50, 100)

# regresa un True si todos los elementos son mayores a 20
print(np.all(x > 10))

False


In [26]:
# Checkin if any of the values in the array satisfy a condition: th np.any function return value True if any of the items satisfy the condition
print(np.any(x > 20))

True


In [27]:
# regresa el index de los elementos que son menores a 10
print(np.where(x < 10))

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18], dtype=int64),)


In [28]:
print(x[np.where(x < 10)])

[1.         1.49494949 1.98989899 2.48484848 2.97979798 3.47474747
 3.96969697 4.46464646 4.95959596 5.45454545 5.94949495 6.44444444
 6.93939394 7.43434343 7.92929293 8.42424242 8.91919192 9.41414141
 9.90909091]


In [31]:
print(x[(x < 10) & (x > 5)])

[5.45454545 5.94949495 6.44444444 6.93939394 7.43434343 7.92929293
 8.42424242 8.91919192 9.41414141 9.90909091]


# Construccion de array con saltos de valor constante floatante

In [4]:
array_3=np.arange(0,4,0.3)
print(array_3)
print(array_3.sum())

[0.  0.3 0.6 0.9 1.2 1.5 1.8 2.1 2.4 2.7 3.  3.3 3.6 3.9]
27.299999999999997


In [5]:
# Funcion reshape, crear dos arrays
array_4=np.arange(0,20).reshape(5,4)
print(array_4)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [8]:
array_lineal=np.linspace(0,50,10)
print(array_lineal)

[ 0.          5.55555556 11.11111111 16.66666667 22.22222222 27.77777778
 33.33333333 38.88888889 44.44444444 50.        ]


In [9]:
random_array=np.random.random((3,3))
print(random_array)

[[0.02724181 0.65532757 0.35442275]
 [0.32232079 0.35478279 0.09690681]
 [0.33060697 0.70002965 0.2308405 ]]


In [16]:
# creacion de array de cuatro elementos consecutivos
a = np.arange(4,8)
b=np.random.random(4)
b=b*10
print(a)
print(b)
print(a+4)
print(a+b)

[4 5 6 7]
[7.40352936 0.53704421 1.75876028 7.16377055]
[ 8  9 10 11]
[11.40352936  5.53704421  7.75876028 14.16377055]
