# Conditions and booleans

In [2]:
import numpy as np

A = np.random.random((4,4))
print(A)

[[0.35028673 0.87719048 0.86837904 0.88807507]
 [0.45459508 0.08010876 0.45649309 0.56210639]
 [0.27012424 0.51819921 0.42045528 0.06088935]
 [0.79368723 0.15871669 0.46458313 0.04127268]]


In [3]:
print(A < 0.5)

[[ True False False False]
 [ True  True  True False]
 [ True False  True  True]
 [False  True  True  True]]


In [4]:
print(A[A < 0.5])

[0.35028673 0.45459508 0.08010876 0.45649309 0.27012424 0.42045528
 0.06088935 0.15871669 0.46458313 0.04127268]


In [8]:
a = np.random.random(12)
a_34=a.reshape(3,4)
print(a,a_34)

[0.96742307 0.58957037 0.9129967  0.11418046 0.41050914 0.09697657
 0.55996253 0.16451991 0.31409899 0.72593344 0.64523727 0.20608883] [[0.96742307 0.58957037 0.9129967  0.11418046]
 [0.41050914 0.09697657 0.55996253 0.16451991]
 [0.31409899 0.72593344 0.64523727 0.20608883]]
