In [14]:
import numpy as np

# Uso de vstack y hstack()

A = np.arange(0,20).reshape(5,4)
ones=np.ones((5,2))
zeros_v1=np.zeros((3,6))
print(np.hstack((A,ones)))
print(zeros_v1)
# np.vstack((A,zeros_v1))

[[ 0.  1.  2.  3.  1.  1.]
 [ 4.  5.  6.  7.  1.  1.]
 [ 8.  9. 10. 11.  1.  1.]
 [12. 13. 14. 15.  1.  1.]
 [16. 17. 18. 19.  1.  1.]]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [28]:
m=np.arange(24).reshape(4,3,2)
m

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])